package design.featuresliced.helper.gui.form.settings.templates.modify;

import com.intellij.ui.components.JBTextArea;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import java.awt.*;

public class TemplateAddEditForm {

    private JPanel root;
    private JTextField nameTextField;
    private JBTextArea descriptionTextArea;

    public TemplateAddEditForm(@Nullable String currentName, @Nullable String description) {
        this.nameTextField.setText(currentName);
        this.descriptionTextArea.setText(description);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        root.setMinimumSize(new Dimension(500, 180));
        root.setName("templateAddEditRoot");
        root.setPreferredSize(new Dimension(500, 180));
        final JLabel label1 = new JLabel();
        label1.setText("Name:");
        root.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameTextField = new JTextField();
        nameTextField.setMargin(new Insets(2, 6, 2, 6));
        nameTextField.setName("nameTextField");
        root.add(nameTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Description:");
        root.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        descriptionTextArea = new JBTextArea();
        descriptionTextArea.setLineWrap(false);
        descriptionTextArea.setMargin(new Insets(2, 6, 2, 6));
        descriptionTextArea.setName("descriptionTextArea");
        descriptionTextArea.setWrapStyleWord(false);
        root.add(descriptionTextArea, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

    public JTextField getNameTextField() {
        return nameTextField;
    }

    public JBTextArea getDescriptionTextArea() {
        return descriptionTextArea;
    }

}
